module

public import Mathlib.Analysis.CStarAlgebra.ContinuousFunctionalCalculus.Basic
open StarAlgebra elemental
noncomputable section
namespace LeanCFC

variable {A : Type*} [CStarAlgebra A]

/-- The ⋆-isomorphism between the continuous functions on the spectrum of `a`
and the (unital) C⋆-subalgebra generated by `a`. -/
def continuousFunctionalCalculus (a : A) [IsStarNormal a] :
    C(spectrum ℂ a, ℂ) ≃⋆ₐ[ℂ] StarAlgebra.elemental ℂ a :=
  characterSpaceHomeo a |>.compStarAlgEquiv' ℂ ℂ |>.trans
    (gelfandStarTransform (elemental ℂ a)).symm

/-- The continuous functional calculus identifies the (restriction of) the
identity function on the spectrum of `a` with `a`. -/
theorem continuousFunctionalCalculus_map_id (a : A) [IsStarNormal a] :
    continuousFunctionalCalculus a ((ContinuousMap.id ℂ).restrict (spectrum ℂ a)) =
      ⟨a, self_mem ℂ a⟩ :=
  gelfandStarTransform (elemental ℂ a) |>.symm_apply_apply _

example {a : A} [IsStarNormal a] : StarAlgebra.elemental ℂ a :=
  continuousFunctionalCalculus a ⟨fun x ↦ Complex.exp x, by fun_prop⟩

example {a : A} [ha : IsStarNormal a] {f : C(spectrum ℂ (a + a), ℂ)} :
    StarAlgebra.elemental ℂ (a + a) :=
  have : IsStarNormal (a + a) := by
    rw [isStarNormal_iff, star_add]
    exact (ha.star_comm_self.add_left ha.star_comm_self).add_right
      (ha.star_comm_self.add_left ha.star_comm_self)
  continuousFunctionalCalculus (a + a) f

example {a b : A} [IsStarNormal a] [IsStarNormal b] :
    (continuousFunctionalCalculus a 0 : A) = continuousFunctionalCalculus b 0 := by
  rw [map_zero, map_zero, ZeroMemClass.coe_zero, ZeroMemClass.coe_zero]

example {u : unitary A} {f : C(Metric.sphere (0 : ℂ) 1, ℂ)} : A :=
  continuousFunctionalCalculus (u : A)
    (f.comp (.inclusion (Unitary.spectrum_subset_circle u)))

/--
error: Tactic `rewrite` failed: motive is not type correct:
  fun _a => (continuousFunctionalCalculus _a) (ContinuousMap.restrict (spectrum ℂ _a) f) = 0
Error: Application type mismatch: The argument
  ha
has type
  IsStarNormal a
but is expected to have type
  IsStarNormal _a
in the application
  @instCommCStarAlgebraSubtypeMemStarSubalgebraComplexOfIsStarNormal A inst✝ _a ⋯

Explanation: The rewrite tactic rewrites an expression 'e' using an equality 'a = b' by the following process. First, it looks for all 'a' in 'e'. Second, it tries to abstract these occurrences of 'a' to create a function 'm := fun _a => ...', called the *motive*, with the property that 'm a' is definitionally equal to 'e'. Third, we observe that 'congrArg' implies that 'm a = m b', which can be used with lemmas such as 'Eq.mpr' to change the goal. However, if 'e' depends on specific properties of 'a', then the motive 'm' might not typecheck.

Possible solutions: use rewrite's 'occs' configuration option to limit which occurrences are rewritten, or use 'simp' or 'conv' mode, which have strategies for certain kinds of dependencies (these tactics can handle proofs and 'Decidable' instances whose types depend on the rewritten term, and 'simp' can apply user-defined '@[congr]' theorems as well).

A : Type u_1
inst✝ : CStarAlgebra A
a b : A
ha : IsStarNormal a
hb : IsStarNormal b
hab : a = b
f : C(ℂ, ℂ)
H : (continuousFunctionalCalculus a) (ContinuousMap.restrict (spectrum ℂ a) f) = 0
⊢ (continuousFunctionalCalculus b) (ContinuousMap.restrict (spectrum ℂ b) f) = 0
-/
#guard_msgs in
example {a b : A} [ha : IsStarNormal a] [hb : IsStarNormal b] (hab : a = b) {f : C(ℂ, ℂ)}
    (H : continuousFunctionalCalculus a (f.restrict (spectrum ℂ a)) = 0) :
    continuousFunctionalCalculus b (f.restrict (spectrum ℂ b)) = 0 := by
  rw [hab] at H -- "motive is not type correct" because of `IsStarNormal a`
  sorry

/--
error: Tactic `rewrite` failed: motive is not type correct:
  fun _a => (continuousFunctionalCalculus _a) f = 0
Error: Application type mismatch: The argument
  f
has type
  C(↑(spectrum ℂ a), ℂ)
but is expected to have type
  C(↑(spectrum ℂ _a), ℂ)
in the application
  (continuousFunctionalCalculus _a) f

Explanation: The rewrite tactic rewrites an expression 'e' using an equality 'a = b' by the following process. First, it looks for all 'a' in 'e'. Second, it tries to abstract these occurrences of 'a' to create a function 'm := fun _a => ...', called the *motive*, with the property that 'm a' is definitionally equal to 'e'. Third, we observe that 'congrArg' implies that 'm a = m b', which can be used with lemmas such as 'Eq.mpr' to change the goal. However, if 'e' depends on specific properties of 'a', then the motive 'm' might not typecheck.

Possible solutions: use rewrite's 'occs' configuration option to limit which occurrences are rewritten, or use 'simp' or 'conv' mode, which have strategies for certain kinds of dependencies (these tactics can handle proofs and 'Decidable' instances whose types depend on the rewritten term, and 'simp' can apply user-defined '@[congr]' theorems as well).

A : Type u_1
inst✝¹ : CStarAlgebra A
B : Type u_2
inst✝ : CommCStarAlgebra B
a b : B
hab : a = b
f : C(↑(spectrum ℂ a), ℂ)
H : (continuousFunctionalCalculus a) f = 0
⊢ (continuousFunctionalCalculus b) (cast ⋯ f) = 0
-/
#guard_msgs in
example {B : Type*} [CommCStarAlgebra B] {a b : B} (hab : a = b) {f : C(spectrum ℂ a, ℂ)}
    (H : continuousFunctionalCalculus a f = 0) :
    continuousFunctionalCalculus b (cast (by rw [hab]) f) = 0 := by
  rw [hab] at H -- "motive is not type correct" because of `spectrum ℂ a`
  sorry

theorem continuousFunctionalCalculus_map_comp {a : A} [IsStarNormal a]
    {f : C(spectrum ℂ a, ℂ)}
    {f' : C(spectrum ℂ a, spectrum ℂ (continuousFunctionalCalculus a f))}
    {g : C(spectrum ℂ (continuousFunctionalCalculus a f), ℂ)}
    (H : ∀ x, f x = f' x) :
    continuousFunctionalCalculus a (g.comp f') =
    continuousFunctionalCalculus (continuousFunctionalCalculus a f) g := by
  sorry

-- this lemma is missing from Mathlib
@[simp]
lemma spectrum.neg_mem_neg {a : A} {x : ℂ} :
    -x ∈ spectrum ℂ (-a) ↔ x ∈ spectrum ℂ a := by
  simp [← spectrum.neg_eq]

-- this lemma is missing from Mathlib
@[fun_prop]
lemma Subtype.continuous_map {α β : Type*} [TopologicalSpace α] [TopologicalSpace β]
    {p : α → Prop} {q : β → Prop} {f : α → β}
    (hf : ∀ x, p x → q (f x)) (h_cont : ContinuousOn f {x | p x}) :
    Continuous (Subtype.map f hf) := by
  simpa [continuous_induced_rng, Function.comp_def]
    using h_cont.comp_continuous (by fun_prop) (by simp)

theorem continuousFunctionalCalculus_map_neg {a : A}
    [IsStarNormal a] (f : C(spectrum ℂ (-a), ℂ)) :
    (continuousFunctionalCalculus (-a) f : A) =
      continuousFunctionalCalculus a (f.comp ⟨Subtype.map (- ·) (by simp), by fun_prop⟩) := by
  sorry
