module

public import Mathlib.Analysis.CStarAlgebra.ContinuousFunctionalCalculus.Basic


/-! # Contrasting statements and proofs in the monomorphism approach to the continuous functional calculus

In this file, we provide examples comparing our approach to the continuous functional calculus
to one more similar to the naive approach describe in Section 4 of the paper.

Unlike the naive approach described in the paper, we reduce the dependent typing somewhat by
utilizing a ⋆-monomorphism from `C(spectrum ℂ a, ℂ)` into `A`, as opposed to the a ⋆-isomorphism
onto the unital C⋆-subalgebra generated by `a`. As a result, the examples here will be *simpler*
than if we were to use the naive approach described in the paper; although as is evidenced below,
these are far from simple, even for toy problems.

We contrast these with examples of the same theorems utilizing our preferred approach. The
statements are uniformly simpler, as are the proofs.
-/


open StarAlgebra elemental CStarAlgebra
noncomputable section
namespace LeanCFC

variable {A : Type*} [CStarAlgebra A]

/-- The ⋆-monomorphism from the continuous functions on the spectrum of `a : A`
into `A` sending the retriction of the identity to `a`. The range is the
(unital) C⋆-subalgebra generated by `a`. -/
def cfcMono (a : A) [IsStarNormal a] :
    C(spectrum ℂ a, ℂ) →⋆ₐ[ℂ] A :=
  (elemental ℂ a).subtype.comp <|
    characterSpaceHomeo a |>.compStarAlgEquiv' ℂ ℂ |>.trans
      (gelfandStarTransform (elemental ℂ a)).symm

/-- The continuous functional calculus identifies the (restriction of) the
identity function on the spectrum of `a` with `a`. -/
theorem cfcMono_map_id (a : A) [IsStarNormal a] :
    cfcMono a ((ContinuousMap.id ℂ).restrict (spectrum ℂ a)) = a :=
  congr(Subtype.val $(gelfandStarTransform (elemental ℂ a) |>.symm_apply_apply ⟨a, self_mem ℂ a⟩))

theorem cfcMono_injective (a : A) [IsStarNormal a] :
    Function.Injective (cfcMono a) :=
  Subtype.val_injective.comp <| RingEquiv.injective _

-- this lemma is missing from Mathlib
@[simp]
lemma spectrum.neg_mem_neg {a : A} {x : ℂ} :
    -x ∈ spectrum ℂ (-a) ↔ x ∈ spectrum ℂ a := by
  simp [← spectrum.neg_eq]

/-- The composition property for `cfcMono`. -/
theorem cfcMono_map_comp {a : A} [IsStarNormal a]
    {f : C(spectrum ℂ a, ℂ)}
    {f' : C(spectrum ℂ a, spectrum ℂ (cfcMono a f : A))}
    {g : C(spectrum ℂ (cfcMono a f : A), ℂ)}
    (H : ∀ x, f x = f' x) :
    cfcMono a (g.comp f') =
      cfcMono (cfcMono a f) g := by
  -- `φ` is the continuous functional calculus for `a` composed with the `StarAlgHom` between
  -- spaces of continuous functions induced by precomposition with `f'`.
  let φ : C(spectrum ℂ (cfcMono a f), ℂ) →⋆ₐ[ℂ] A :=
    StarAlgHom.comp (cfcMono a) (ContinuousMap.compStarAlgHom' ℂ ℂ f')
  -- `ψ` is the continuous functional calculus for `cfcMono a f`
  let ψ : C(spectrum ℂ (cfcMono a f), ℂ) →⋆ₐ[ℂ] A :=
      cfcMono (cfcMono a f)
  -- By the Stone--Weierstrass theorem, if `φ` and `ψ` agree on the restriction of the identity,
  -- then they must be equal (and hence equal at evaluation at `g`.)
  refine congr($(φ.ext_continuousMap _ ψ (by fun_prop) (by fun_prop) ?_) g)
  -- Indeed, `φ` and `ψ` agree on the restriction of the identity
  trans cfcMono a f
  · simp only [φ, StarAlgHom.comp_apply, ContinuousMap.compStarAlgHom'_apply]
    congr!
    ext x
    simp [H]
  · exact cfcMono_map_id _ |>.symm

/-- If two normal elements are equal, their continuous functional calculi differ by precomposition
with the canonical homeomorphism (i.e., the identity map) between their spectra. -/
lemma cfcMono_congr {a b : A} [IsStarNormal a] [IsStarNormal b] (h : a = b) :
    cfcMono b =
      (cfcMono a).comp
        (ContinuousMap.compStarAlgHom' ℂ ℂ (Homeomorph.setCongr (congr(spectrum ℂ $h)))) := by
  refine (cfcMono b).ext_continuousMap _ _ (by fun_prop) (by fun_prop) ?_
  rw [cfcMono_map_id]
  exact Eq.symm <| (cfcMono_map_id a).trans h

lemma cfcMono_congr_apply {a b : A} [IsStarNormal a] [IsStarNormal b]
    (h : a = b) (f : C(spectrum ℂ b, ℂ)) :
    cfcMono b f = cfcMono a (f.comp (Homeomorph.setCongr (congr(spectrum ℂ $h)))) :=
  congr($(cfcMono_congr h) f)

/-- The composition property mediated by an equality for the continuous functional calculus applied to some element.
This is likely more useful than `cfcMono_map_comp` above, but it still requires mention both of
the function `f` and the selected co-restriction `f'`, making it rather cumbersome to use in practice; see
`cfcMono_map_neg` below. -/
theorem cfcMono_map_comp_of_eq {a b : A} [IsStarNormal a] [IsStarNormal b]
    {f : C(spectrum ℂ a, ℂ)} (hab : b = cfcMono a f)
    {f' : C(spectrum ℂ a, spectrum ℂ b)} {g : C(spectrum ℂ b, ℂ)} (H : ∀ x, f x = f' x) :
    cfcMono a (g.comp f') = cfcMono b g := by
  rw [cfcMono_congr_apply hab.symm]
  rw [← cfcMono_map_comp (f' := .comp (Homeomorph.setCongr (congr(spectrum ℂ $hab.symm))).symm f' )]
  · rfl
  · exact H

/-- This is the theorem $$f(-a) = (x ↦ f(-x))(a)$$, which is the composition property when the
inner function is negation. Note that the corestriction of negation is not just a detail of the
proof, but appears in the statement. -/
theorem cfcMono_map_neg {a : A}
    [IsStarNormal a] (f : C(spectrum ℂ (-a), ℂ)) :
    cfcMono (-a) f =
      cfcMono a (f.comp
        ⟨Subtype.coind (- · : spectrum ℂ a → ℂ) (by simp), by fun_prop⟩) := by
  refine Eq.symm <| cfcMono_map_comp_of_eq (a := a) (b := -a) (g := f)
    (f := ⟨(- ·), by fun_prop⟩) ?_ (fun _ ↦ rfl)
  conv_lhs => rw [← cfcMono_map_id a, ← map_neg]
  rfl

/-- A variant of the previous lemma which assumes `f : C(spectrum ℂ a, ℂ)`. -/
theorem cfcMono_map_neg' {a : A}
    [IsStarNormal a] (f : C(spectrum ℂ a, ℂ)) :
    cfcMono (-a)
      (f.comp ⟨Subtype.coind (- · : spectrum ℂ (-a) → ℂ)
        (by intro ⟨x, hx⟩; simpa [← spectrum.neg_eq] using hx), by fun_prop⟩) =
          cfcMono a f := by
  refine cfcMono_map_comp_of_eq (a := -a) (b := a) (g := f)
    (f := ⟨(- ·), by fun_prop⟩) ?_ (fun _ ↦ rfl)
  rw [cfcMono_map_neg]
  convert cfcMono_map_id a |>.symm
  ext
  simp

-- The same lemmas as the previous two, but using our version of the continuous functional caluclus
-- Note the difference in complexity *both* in the _statement_ and the _proof_.
lemma cfc_map_neg {a : A} [IsStarNormal a] (f : ℂ → ℂ) (hf : ContinuousOn f (spectrum ℂ (-a))) :
    cfc f (-a) = cfc (fun x ↦ f (-x)) a := by
  rw [← spectrum.neg_eq] at hf
  rw [cfc_comp' f (- ·) a (hg := by simpa), cfc_neg, cfc_id' ..]

lemma cfc_map_neg' {a : A} [IsStarNormal a] (f : ℂ → ℂ) (hf : ContinuousOn f (spectrum ℂ a)) :
    cfc (fun x ↦ f (-x)) (-a) = cfc f a := by
  rw [← cfc_map_neg (hf := by simpa), neg_neg]


/-
We would like to say that these are equal, but we can't since the domain of `f` must
be different (i.e., `spectrum ℂ a` versus `spectrum ℂ (- (-a))`, which are provably equal,
but not definitionally so, therefore *as types* they are _homeomorphic_, but not _equal_).

Moreover, the proof is pretty annoying even after we use
`cfcMono_map_neg` twice. You would hope that it would be possible
to prove that you can simply call `neg_neg`, but there is a great deal of shuffling which
must occur before that lemma is used in the final `simp` call.

Compare this with the analogous lemma in `Snippets/Intermediate.lean`, where the
statement and two different proof are exactly as simple as you would hope.
-/
example {a : A} [IsStarNormal a] (f : C(spectrum ℂ a, ℂ)) :
    cfcMono a f =
      cfcMono (- (-a)) (f.comp ⟨Subtype.map id (by simp), by fun_prop⟩) := by
  rw [cfcMono_map_neg, cfcMono_map_neg]
  congr
  simp only [ContinuousMap.comp_assoc]
  convert ContinuousMap.comp_id f |>.symm
  ext
  simp

-- The same lemma as the previous example, but using our version of the continuous functional caluclus
-- Note the difference in complexity *both* in the _statement_ and the _proof_.
-- In fact, because of junk values, the hypothesis `hf` is actually unnecessary, so we silence the linter
set_option linter.unusedVariables false in
example (a : A) [IsStarNormal a] (f : ℂ → ℂ) (hf : ContinuousOn f (spectrum ℂ a)) :
    cfc f a = cfc f (-(-a)) := by
  rw [neg_neg]

theorem cfcMono_map_star {a : A}
    [IsStarNormal a] (f : C(spectrum ℂ (star a), ℂ)) :
    cfcMono (star a) f =
      cfcMono a
        (f.comp ⟨Subtype.coind (star · : spectrum ℂ a → ℂ) (by simp [spectrum.map_star]), by fun_prop⟩) := by
  refine Eq.symm <| cfcMono_map_comp_of_eq (a := a) (b := star a) (g := f)
    (f := ⟨(star ·), by fun_prop⟩) ?_ (fun _ ↦ rfl)
  conv_lhs => rw [← cfcMono_map_id a, ← map_star]
  rfl

example {a : A} [IsStarNormal a] (f : C(spectrum ℂ (star (-a)), ℂ)) :
    cfcMono (star (- a)) f =
      cfcMono (- (star a))
        (f.comp ((by
          have : - (star a) = star (-a) := by simp
          exact ↑(Homeomorph.setCongr congr(spectrum ℂ $this))))) := by
  rw [cfcMono_map_star, cfcMono_map_neg]
  rw [cfcMono_map_neg, cfcMono_map_star]
  congr -- only works because `star (-f) = - (star f)` for functions `f`

-- The same lemma as the previous example, but using our version of the continuous functional caluclus
-- Note the difference in complexity *both* in the _statement_ and the _proof_. Moreover, notice how
-- the proof uses existing API lemmas from Mahlib, not bespoke lemmas.
-- In fact, because of junk values, the hypothesis `hf` is actually unnecessary, so we silence the linter
set_option linter.unusedVariables false in
example {a : A} [IsStarNormal a] (f : ℂ → ℂ) (hf : ContinuousOn f (spectrum ℂ (star (-a)))) :
    cfc f (star (-a)) = cfc f (- (star a)) := by
  rw [star_neg]

-- this is missing from Mathlib
instance {a : A} [IsStarNormal a] (n : ℕ) : IsStarNormal (a ^ n) where
  star_comm_self := star_pow a n ▸ star_comm_self.pow_pow n n

theorem cfcMono_map_pow [Nontrivial A] {a : A}
    [IsStarNormal a] (n : ℕ) (f : C(spectrum ℂ (a ^ n), ℂ)) :
    cfcMono (a ^ n) f =
      cfcMono a
        (f.comp ⟨Subtype.coind (· ^ n : spectrum ℂ a → ℂ) (by simp [spectrum.map_pow]; aesop), by fun_prop⟩) := by
  refine Eq.symm <| cfcMono_map_comp_of_eq (a := a) (b := a ^ n) (g := f)
    (f := ⟨(· ^ n), by fun_prop⟩) ?_ (fun _ ↦ rfl)
  conv_lhs => rw [← cfcMono_map_id a, ← map_pow]
  rfl

-- this is a nice example of how the blow-up in mess occurs, even in the
-- context of toy problems.
example {a : A} [IsStarNormal a] [Nontrivial A] (f : C(spectrum ℂ ((-a) ^ 3), ℂ)) :
    cfcMono ((- a) ^ 3) f =
      cfcMono (- (a ^ 3))
        (f.comp ((by
          have : - (a ^ 3) = (-a) ^ 3 := by simp [pow_succ]
          exact ↑(Homeomorph.setCongr congr(spectrum ℂ $this))))) := by
  rw [cfcMono_map_pow 3, cfcMono_map_neg]
  rw [cfcMono_map_neg, cfcMono_map_pow 3]
  simp
  congr! 2
  ext ⟨x, hx⟩
  simp [pow_succ]
  rfl

-- The same lemma as the previous example, but using our version of the continuous functional caluclus
-- Note the difference in complexity *both* in the _statement_ and the _proof_.
-- In fact, because of junk values, the hypothesis `hf` is actually unnecessary, so we silence the linter
set_option linter.unusedVariables false in
example (a : A) [IsStarNormal a] (f : ℂ → ℂ) (hf : ContinuousOn f (spectrum ℂ a)) :
    cfc f ((- a) ^ 3) = cfc f (-(a ^ 3)) := by
  rw [Odd.neg_pow (by decide)]
