module

public import Mathlib.Analysis.CStarAlgebra.ContinuousFunctionalCalculus.Basic


/-! # Contrasting statements and proofs in the monomorphism approach to the continuous functional calculus

In this file, we provide examples comparing our approach to the continuous functional calculus
to one more similar to the naive approach describe in Section 4 of the paper.

Unlike the naive approach described in the paper, we reduce the dependent typing somewhat by
utilizing a ⋆-monomorphism from `C(spectrum ℂ a, ℂ)` into `A`, as opposed to the a ⋆-isomorphism
onto the unital C⋆-subalgebra generated by `a`. As a result, the examples here will be *simpler*
than if we were to use the naive approach described in the paper; although as is evidenced below,
these are far from simple, even for toy problems.

We contrast these with examples of the same theorems utilizing our preferred approach. The
statements are uniformly simpler, as are the proofs.
-/


open StarAlgebra elemental CStarAlgebra
noncomputable section
namespace LeanCFC

variable {A : Type*} [CStarAlgebra A]

/-- The ⋆-monomorphism from the continuous functions on the spectrum of `a : A`
into `A` sending the retriction of the identity to `a`. The range is the
(unital) C⋆-subalgebra generated by `a`. -/
def cfcMono (a : A) [IsStarNormal a] :
    C(spectrum ℂ a, ℂ) →⋆ₐ[ℂ] A :=
  (elemental ℂ a).subtype.comp <|
    characterSpaceHomeo a |>.compStarAlgEquiv' ℂ ℂ |>.trans
      (gelfandStarTransform (elemental ℂ a)).symm

/-- The continuous functional calculus identifies the (restriction of) the
identity function on the spectrum of `a` with `a`. -/
theorem cfcMono_map_id (a : A) [IsStarNormal a] :
    cfcMono a ((ContinuousMap.id ℂ).restrict (spectrum ℂ a)) = a :=
  congr(Subtype.val $(gelfandStarTransform (elemental ℂ a) |>.symm_apply_apply ⟨a, self_mem ℂ a⟩))

theorem cfcMono_injective (a : A) [IsStarNormal a] :
    Function.Injective (cfcMono a) :=
  Subtype.val_injective.comp <| RingEquiv.injective _

-- this lemma is missing from Mathlib
@[simp]
lemma spectrum.neg_mem_neg {a : A} {x : ℂ} :
    -x ∈ spectrum ℂ (-a) ↔ x ∈ spectrum ℂ a := by
  simp [← spectrum.neg_eq]

/-- The composition property for `cfcMono`. -/
theorem cfcMono_map_comp {a : A} [IsStarNormal a]
    {f : C(spectrum ℂ a, ℂ)}
    {f' : C(spectrum ℂ a, spectrum ℂ (cfcMono a f : A))}
    {g : C(spectrum ℂ (cfcMono a f : A), ℂ)}
    (H : ∀ x, f x = f' x) :
    cfcMono a (g.comp f') =
      cfcMono (cfcMono a f) g := by
  -- `φ` is the continuous functional calculus for `a` composed with the `StarAlgHom` between
  -- spaces of continuous functions induced by precomposition with `f'`.
  let φ : C(spectrum ℂ (cfcMono a f), ℂ) →⋆ₐ[ℂ] A :=
    StarAlgHom.comp (cfcMono a) (ContinuousMap.compStarAlgHom' ℂ ℂ f')
  -- `ψ` is the continuous functional calculus for `cfcMono a f`
  let ψ : C(spectrum ℂ (cfcMono a f), ℂ) →⋆ₐ[ℂ] A := cfcMono (cfcMono a f)
  -- By the Stone--Weierstrass theorem, if `φ` and `ψ` agree on the restriction of the identity,
  -- then they must be equal (and hence equal at evaluation at `g`.)
  refine congr($(φ.ext_continuousMap _ ψ (by fun_prop) (by fun_prop) ?_) g)
  -- Indeed, `φ` and `ψ` agree on the restriction of the identity
  trans cfcMono a f
  · simp only [φ, StarAlgHom.comp_apply, ContinuousMap.compStarAlgHom'_apply]
    congr!
    ext x
    simp [H]
  · exact cfcMono_map_id _ |>.symm

/-- If two normal elements are equal, their continuous functional calculi differ by precomposition
with the canonical homeomorphism (i.e., the identity map) between their spectra. -/
lemma cfcMono_congr {a b : A} [IsStarNormal a] [IsStarNormal b] (h : a = b) :
    cfcMono b =
      (cfcMono a).comp
        (ContinuousMap.compStarAlgHom' ℂ ℂ (Homeomorph.setCongr (congr(spectrum ℂ $h)))) := by
  refine (cfcMono b).ext_continuousMap _ _ (by fun_prop) (by fun_prop) ?_
  rw [cfcMono_map_id]
  exact Eq.symm <| (cfcMono_map_id a).trans h

lemma cfcMono_congr_apply {a b : A} [IsStarNormal a] [IsStarNormal b]
    (h : a = b) (f : C(spectrum ℂ b, ℂ)) :
    cfcMono b f = cfcMono a (f.comp (Homeomorph.setCongr (congr(spectrum ℂ $h)))) :=
  congr($(cfcMono_congr h) f)

/-- The composition property mediated by an equality for the continuous functional calculus applied to some element.
This is likely more useful than `cfcMono_map_comp` above, but it still requires mention both of
the function `f` and the selected co-restriction `f'`, making it rather cumbersome to use in practice; see
`cfcMono_map_neg` below. -/
theorem cfcMono_map_comp_of_eq {a b : A} [IsStarNormal a] [IsStarNormal b]
    {f : C(spectrum ℂ a, ℂ)} (hab : b = cfcMono a f)
    {f' : C(spectrum ℂ a, spectrum ℂ b)} {g : C(spectrum ℂ b, ℂ)} (H : ∀ x, f x = f' x) :
    cfcMono a (g.comp f') = cfcMono b g := by
  rw [cfcMono_congr_apply hab.symm]
  rw [← cfcMono_map_comp (f' := .comp (Homeomorph.setCongr (congr(spectrum ℂ $hab.symm))).symm f' )]
  · rfl
  · exact H

/-- This is the theorem $$f(-a) = (x ↦ f(-x))(a)$$, which is the composition property when the
inner function is negation. Note that the corestriction of negation is not just a detail of the
proof, but appears in the statement. -/
theorem cfcMono_map_neg {a : A}
    [IsStarNormal a] (f : C(spectrum ℂ (-a), ℂ)) :
    cfcMono (-a) f =
      cfcMono a (f.comp
        ⟨Subtype.coind (- · : spectrum ℂ a → ℂ) (by simp), by fun_prop⟩) := by
  refine Eq.symm <| cfcMono_map_comp_of_eq (a := a) (b := -a) (g := f)
    (f := ⟨(- ·), by fun_prop⟩) ?_ (fun _ ↦ rfl)
  conv_lhs => rw [← cfcMono_map_id a, ← map_neg]
  rfl

/-- A variant of the previous lemma which assumes `f : C(spectrum ℂ a, ℂ)`. -/
theorem cfcMono_map_neg' {a : A}
    [IsStarNormal a] (f : C(spectrum ℂ a, ℂ)) :
    cfcMono (-a)
      (f.comp ⟨Subtype.coind (- · : spectrum ℂ (-a) → ℂ)
        (by intro ⟨x, hx⟩; simpa [← spectrum.neg_eq] using hx), by fun_prop⟩) =
          cfcMono a f := by
  refine cfcMono_map_comp_of_eq (a := -a) (b := a) (g := f)
    (f := ⟨(- ·), by fun_prop⟩) ?_ (fun _ ↦ rfl)
  rw [cfcMono_map_neg]
  convert cfcMono_map_id a |>.symm
  ext
  simp

-- The same lemmas as the previous two, but using our version of the continuous functional caluclus
-- Note the difference in complexity *both* in the _statement_ and the _proof_.
lemma cfc_map_neg {a : A} [IsStarNormal a] (f : ℂ → ℂ)
    (hf : ContinuousOn f (spectrum ℂ (-a))) :
    cfc f (-a) = cfc (fun x ↦ f (-x)) a := by
  rw [← spectrum.neg_eq] at hf
  rw [cfc_comp' f (- ·) a (hg := by simpa), cfc_neg, cfc_id' ..]

lemma cfc_map_neg' {a : A} [IsStarNormal a] (f : ℂ → ℂ) (hf : ContinuousOn f (spectrum ℂ a)) :
    cfc (fun x ↦ f (-x)) (-a) = cfc f a := by
  rw [← cfc_map_neg (hf := by simpa), neg_neg]

theorem cfcMono_map_star {a : A}
    [IsStarNormal a] (f : C(spectrum ℂ (star a), ℂ)) :
    cfcMono (star a) f =
      cfcMono a
        (f.comp ⟨Subtype.coind (star · : spectrum ℂ a → ℂ) (by simp [spectrum.map_star]), by fun_prop⟩) := by
  refine Eq.symm <| cfcMono_map_comp_of_eq (a := a) (b := star a) (g := f)
    (f := ⟨(star ·), by fun_prop⟩) ?_ (fun _ ↦ rfl)
  conv_lhs => rw [← cfcMono_map_id a, ← map_star]
  rfl

/-- A variant of the previous lemma which assumes `f : C(spectrum ℂ a, ℂ)`. -/
theorem cfcMono_map_star' {a : A}
    [IsStarNormal a] (f : C(spectrum ℂ a, ℂ)) :
    cfcMono (star a)
      (f.comp ⟨Subtype.coind (star · : spectrum ℂ (star a) → ℂ)
        (by simp [spectrum.map_star]), by fun_prop⟩) =
          cfcMono a f := by
  refine cfcMono_map_comp_of_eq (a := star a) (b := a) (g := f)
    (f := ⟨(star ·), by fun_prop⟩) ?_ (fun _ ↦ rfl)
  rw [cfcMono_map_star]
  convert cfcMono_map_id a |>.symm
  ext
  simp

-- The same lemmas as the previous two, but using our version of the continuous functional caluclus
-- Note the difference in complexity *both* in the _statement_ and the _proof_.
lemma cfc_map_star {a : A} [IsStarNormal a] (f : ℂ → ℂ) (hf : ContinuousOn f (spectrum ℂ (star a))) :
    cfc f (star a) = cfc (fun x ↦ f (star x)) a := by
  rw [spectrum.map_star] at hf
  rw [cfc_comp' f (star ·) a (hg := by rwa [Set.image_star]), cfc_star, cfc_id' ..]

lemma cfc_map_star' {a : A} [IsStarNormal a] (f : ℂ → ℂ) (hf : ContinuousOn f (spectrum ℂ a)) :
    cfc (fun x ↦ f (star x)) (star a) = cfc f a := by
  rw [← cfc_map_star (hf := by simpa), star_star]

/-
We would like to say that these are equal using the same function `f`, but that would not be type
correct since the domain of `f` must be different (i.e., `spectrum ℂ a` versus `spectrum ℂ (- (-a))`,
which are provably equal, but not definitionally so, therefore *as types* they are _homeomorphic_,
but not _equal_).
-/
example {a : A} [IsStarNormal a] (f : C(spectrum ℂ a, ℂ)) :
    cfcMono a f =
      cfcMono (- (-a)) (f.comp ⟨Subtype.map id (by simp), by fun_prop⟩) :=
  Eq.symm <| cfcMono_congr_apply (neg_neg a).symm (f.comp ⟨Subtype.map id (by simp), by fun_prop⟩)

/- The same lemma as the previous example, but using our version of the continuous functional caluclus
Note the difference in complexity *both* in the _statement_ and the _proof_.
In fact, because of junk values, the hypothesis `hf` is actually unnecessary, so we silence the linter -/
set_option linter.unusedVariables false in
example (a : A) [IsStarNormal a] (f : ℂ → ℂ) (hf : ContinuousOn f (spectrum ℂ a)) :
    cfc f a = cfc f (-(-a)) := by
  rw [neg_neg]

/- the proof here only works so easily because of the specific form of the function we compose with `f`.
compare to the example with `-(-a)` and `a` above, where the function was not a coercion of
`Homeomorph.setCongr` -/
example {a : A} [IsStarNormal a] (f : C(spectrum ℂ (star (-a)), ℂ)) :
    cfcMono (star (- a)) f =
      cfcMono (- (star a))
        (f.comp ((by
          have : - (star a) = star (-a) := by simp
          exact ↑(Homeomorph.setCongr congr(spectrum ℂ $this))))) := by
  rw [← cfcMono_congr_apply (by simp)]

/- The same lemma as the previous example, but using our version of the continuous functional caluclus
Note the difference in complexity in the _statement_. Notice also how the proof uses existing API
lemmas from Mahlib, not bespoke lemmas for `cfcMono`. In fact, because of junk values, the
hypothesis `hf` is actually unnecessary, so we silence the linter. -/
set_option linter.unusedVariables false in
example {a : A} [IsStarNormal a] (f : ℂ → ℂ) (hf : ContinuousOn f (spectrum ℂ (star (-a)))) :
    cfc f (star (-a)) = cfc f (- (star a)) := by
  rw [star_neg]

-- this is missing from Mathlib
instance (a : A) [IsStarNormal a] (n : ℕ) : IsStarNormal (a ^ n) where
  star_comm_self := star_pow a n ▸ star_comm_self.pow_pow n n

/- this works, but basically because the setting is slightly too easy. Here we have something
*very* nice on the LHS, which will match our theorem statements, so Lean is easily appeased. -/
example {a : A} [IsStarNormal a] [Nontrivial A] (f : C(spectrum ℂ ((-a) ^ 3), ℂ)) :
    cfcMono ((-a) ^ 3) f =
      cfcMono (-(a ^ 3))
        (f.comp ((by
          have : -(a ^ 3) = (-a) ^ 3 := by simp [pow_succ]
          exact ↑(Homeomorph.setCongr congr(spectrum ℂ $this))))) := by
  rw [← cfcMono_congr_apply (by grind)]

/- For comparison, this is the same statement and proof using our approach. -/
example {a : A} [IsStarNormal a] (f : ℂ → ℂ) (hf : ContinuousOn f (spectrum ℂ ((-a) ^ 3))) :
    cfc f ((-a) ^ 3) = cfc (fun x ↦ f (-x)) (a ^ 3) := by
  rw [Odd.neg_pow (by decide)] at hf ⊢
  rw [cfc_map_neg _ hf]

/- Again, this works without too much effort because one of the sides is well-behaved. -/
example {a : A} [IsStarNormal a] [Nontrivial A] (f : C(spectrum ℂ ((-a) ^ 3), ℂ)) :
    cfcMono ((-a) ^ 3) f =
    cfcMono (a ^ 3) (f.comp
      ⟨Subtype.coind (- · : spectrum ℂ (a ^ 3) → ℂ)
        (by simp [Odd.neg_pow (n := 3) (by decide)]), by fun_prop⟩) := by
  rw [cfcMono_congr_apply (Odd.neg_pow (n := 3) (by decide) a).symm, cfcMono_map_neg]
  congr

/- For comparison, this is the same statement and proof using our approach. -/
example {a : A} [IsStarNormal a] (f : ℂ → ℂ) (hf : ContinuousOn f (spectrum ℂ ((-a) ^ 3))) :
    cfc f ((-a) ^ 3) = cfc (fun x ↦ f (-x)) (a ^ 3) := by
  rw [← cfc_map_neg] <;> rw [Odd.neg_pow (by decide)] at *
  assumption

/- Here is our first example, where we want to show that
`cfc (fun x ↦ f (-x)) ((-a) ^ 3) = cfc f (a ^ 3)`.
Note that it's quite hard to get any rewrites to work involving `cfcMono_congr_apply`,
and this proof is brittle.
Moreover, we have to use the lemma `cfcMono_map_neg'` in *reverse* because it's the only
version which is general enough to unify. -/
example {a : A} [IsStarNormal a] [Nontrivial A] (f : C(spectrum ℂ (a ^ 3), ℂ)) :
    cfcMono ((-a) ^ 3) (f.comp
      ⟨Subtype.coind (- · : spectrum ℂ ((-a) ^ 3) → ℂ)
        (by simp [Odd.neg_pow (n := 3) (by decide), ← spectrum.neg_eq]), by fun_prop⟩) =
    cfcMono (a ^ 3) f := by
  rw [← cfcMono_map_neg' f]
  convert (cfcMono_congr_apply ?_ _).symm using 2
  · ext
    rfl
  · grind

/- For comparison, here is the exact same theorem using our approach. Note the simplicity of
both the statement and the proof. -/
example {a : A} [IsStarNormal a] (f : ℂ → ℂ) (hf : ContinuousOn f (spectrum ℂ (a ^ 3))) :
    cfc (fun x ↦ f (-x)) ((-a) ^ 3) = cfc f (a ^ 3) := by
  rwa [Odd.neg_pow (by decide), cfc_map_neg']

/- As the complexity of the problems grows even modestly, the `cfcMono` approach becomes
absolutely unwieldy and the explodes into a mess.

Note that in order to make the statement even somewhat readable, we need to extract out,
into `haveI` statements, two of the proofs necessary to make the statement type check.

If you're having trouble even parsing the statement, see the next example which does the same
thing using our approach.

In the proof, we have to be very careful when using `rw` lemmas. We have to use
`cfcMono_map_neg'` and `cfcMono_map_star'` in the *reverse* directions because it is only the
right-hand side of those lemmas which are generic enough to match. We effectively add more
and more complexity to the goal state until we finally collapse it at the end of the proof.
See, for example, the goal state prior to `congr! 1`. -/
example {a : A} [IsStarNormal a] (f : C(spectrum ℂ ((-star a) ^ 3), ℂ)) :
    haveI h₁ (x : spectrum ℂ ((-a) ^ 3)) : star ↑x ∈ spectrum ℂ ((-star a) ^ 3) := by
      simp only [← star_neg, ← star_pow, spectrum.map_star, Set.star_mem_star]
      exact x.2
    haveI h₂ (x : spectrum ℂ (star a ^ 3)) : -↑x ∈ spectrum ℂ ((-star a) ^ 3) := by
      simp only [Odd.neg_pow (n := 3) (by decide), ← spectrum.neg_eq, Set.neg_mem_neg]
      exact x.2
    cfcMono ((-a) ^ 3) (f.comp
      ⟨Subtype.coind (star · : spectrum ℂ ((-a) ^ 3) → ℂ) h₁, by fun_prop⟩) =
    cfcMono (star a ^ 3) (f.comp
      ⟨Subtype.coind (- · : spectrum ℂ (star a ^ 3) → ℂ) h₂, by fun_prop⟩) := by
  conv_rhs => rw [← cfcMono_map_neg']
  conv_lhs => rw [← cfcMono_map_star']
  rw [cfcMono_congr_apply (b := star ((-a) ^ 3)) (a := -star a ^ 3) ?h_eq]
  case h_eq => simp [Odd.neg_pow (n := 3) (by decide)]
  congr! 1
  ext
  simp [Subtype.coind, Homeomorph.setCongr]

/- For comparison, in our approach, the statement of the above is trivial.
Note that the proofs of `h₁` and `h₂` in the *statement* of the previous version now appear
(and simpler!) in the *proof* of this result. Notice also that all the extraneous bits from
the previous proof are absent. -/
example {a : A} [IsStarNormal a] (f : ℂ → ℂ)
    (hf : ContinuousOn f (spectrum ℂ ((-star a) ^ 3))) :
    cfc (fun x ↦ f (star x)) ((-a) ^ 3) = cfc (fun x ↦ f (-x)) (star a ^ 3) := by
  rw [cfc_comp_star (hf := ?hf₁), cfc_comp_neg (hf := ?hf₂)]
  case hf₁ => rwa [Set.image_star, ← spectrum.map_star, star_pow, star_neg]
  case hf₂ => rwa [Set.image_neg_eq_neg, spectrum.neg_eq, ← Odd.neg_pow (by decide)]
  simp [Odd.neg_pow (n := 3) (by decide)]

/- If `f` happens to be globally continuous, then the statement of the previous result in the
`cfcMono` paradigm becomes much simpler, but the proof is unchanged. -/
example {a : A} [IsStarNormal a] (f : C(ℂ, ℂ)) :
    cfcMono ((-a) ^ 3) ((f.comp (star (.id ℂ))).restrict (spectrum ℂ ((-a) ^ 3))) =
    cfcMono (star a ^ 3) ((f.comp (- (.id ℂ))).restrict (spectrum ℂ (star a ^ 3))) := by
  conv_rhs => rw [← cfcMono_map_neg']
  conv_lhs => rw [← cfcMono_map_star']
  rw [cfcMono_congr_apply (b := star ((-a) ^ 3)) (a := -star a ^ 3) ?h_eq]
  case h_eq => simp [Odd.neg_pow (n := 3) (by decide)]
  congr! 1
  ext ⟨x, hx⟩
  simp [Subtype.coind, Homeomorph.setCongr]

/- In contrast, in our approach, if `f` happens to be continuous globally,
Then the statment (modulo a small change in hypothesis) is the same, and the proof becomes
even simpler. -/
example {a : A} [IsStarNormal a] (f : ℂ → ℂ) (hf : Continuous f) :
    cfc (fun x ↦ f (star x)) ((-a) ^ 3) = cfc (fun x ↦ f (-x)) ((star a) ^ 3) := by
  rw [cfc_comp_star .., cfc_comp_neg ..]
  simp [Odd.neg_pow (n := 3) (by decide)]
